name: BlueMapMarkers
api-version: "1.13"
main: net.okocraft.bluemapmarkers.BlueMapMarkersPlugin
version: ${projectVersion}
author: Siroshun09
folia-supported: true

depend: [ BlueMap ]
softdepend: [ WorldGuard ]
